"""Added place column

Revision ID: 1b9e2ba49c66
Revises: 
Create Date: 2025-04-13 13:10:53.465693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9e2ba49c66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('emergency_contact')
    op.drop_table('safety_feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lon', sa.FLOAT(), nullable=True),
    sa.Column('safety', sa.VARCHAR(length=50), nullable=True),
    sa.Column('recommend', sa.VARCHAR(length=10), nullable=True),
    sa.Column('police_patrol', sa.VARCHAR(length=50), nullable=True),
    sa.Column('crime_witnessed', sa.VARCHAR(length=10), nullable=True),
    sa.Column('crime_description', sa.TEXT(), nullable=True),
    sa.Column('police_presence', sa.VARCHAR(length=10), nullable=True),
    sa.Column('road_safety', sa.VARCHAR(length=10), nullable=True),
    sa.Column('traffic_issues', sa.VARCHAR(length=100), nullable=True),
    sa.Column('traffic_signs', sa.VARCHAR(length=10), nullable=True),
    sa.Column('lighting', sa.VARCHAR(length=50), nullable=True),
    sa.Column('security_cameras', sa.VARCHAR(length=10), nullable=True),
    sa.Column('road_condition', sa.VARCHAR(length=10), nullable=True),
    sa.Column('crowd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('suspicious_activity', sa.VARCHAR(length=10), nullable=True),
    sa.Column('homeless_presence', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
